
import java.awt.print.PrinterException;
import static java.lang.Integer.parseInt;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luxar
 */
public class POS extends javax.swing.JFrame {


    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //=======================================Function============================================================
    
    
    public void ItemCost()
    {
        double sum = 0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtTotal1.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtTotal1.getText());
        
        double cTax = (cTotal1 * 0/100);
        
        String iTotal = String.format("₱ %.2f", cTotal1);
        jtxtTotal1.setText(iTotal);
    }
    
    //===========================================Function=========================================================
    
    public void Change()
    {
        double sum = 0;
        double tax = 0;
        double cash = Double.parseDouble(jtxtCash.getText());
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 0)/100;
        double cChange = (cash -(sum + cTax));
        
        String ChangeGiven = String.format("₱ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
       
        
    }
    
    public void bill()
    {
        String total = jtxtTotal1.getText();
        String Change = jtxtChange.getText();
        String Cash = jtxtCash.getText();
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jTable1.getModel();
        
        txtbill.setText(txtbill.getText () + "==============================================\n");
        txtbill.setText(txtbill.getText () + "                POS BILL RECEIPT              \n");
        txtbill.setText(txtbill.getText () + "==============================================\n");
        
        
       
        txtbill.setText(txtbill.getText() + "Product" + "\t" + "Price" + "\n");
        
        
        for (int i = 0; i < model.getRowCount(); i++)
        {
            
            String product = model.getValueAt(i, 0).toString();
            String price =   model.getValueAt(i, 2).toString();
                 
            txtbill.setText(txtbill.getText() + product + "\t" + price + "\n"  );
        
        }
        
         txtbill.setText(txtbill.getText() + "\n");
         txtbill.setText(txtbill.getText() + "\n");
         
         txtbill.setText(txtbill.getText() + "\t" + "\t" + "Total :" + total + "\n");
         txtbill.setText(txtbill.getText() + "\t" + "\t" + "Cash :" + Cash + "\n");
         txtbill.setText(txtbill.getText() + "\t" + "\t" + "Change :" + Change + "\n");
         txtbill.setText(txtbill.getText() + "\n");
         txtbill.setText(txtbill.getText() +"==============================================\n");
         txtbill.setText(txtbill.getText() +"             Thank You Come Again             \n");

         
  
    }
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnWilkins = new javax.swing.JButton();
        jbtnPiatos = new javax.swing.JButton();
        jbtnChippy = new javax.swing.JButton();
        jbtnNova = new javax.swing.JButton();
        jbtnMrChips = new javax.swing.JButton();
        jbtnCoke = new javax.swing.JButton();
        jbtnPepsi = new javax.swing.JButton();
        jbtnSprite = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jtxtTotal1 = new javax.swing.JTextField();
        jbtnPay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtCash = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnWilkins.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnWilkins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wilkins water.jpeg"))); // NOI18N
        jbtnWilkins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWilkinsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnWilkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 270, 170));

        jbtnPiatos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPiatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0001318_6826_ph-piattos-cheese_480.jpeg"))); // NOI18N
        jbtnPiatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPiatosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPiatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 170));

        jbtnChippy.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChippy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chippy.jpeg"))); // NOI18N
        jbtnChippy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChippyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChippy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, 170));

        jbtnNova.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nova chip.jpeg"))); // NOI18N
        jbtnNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 270, 170));

        jbtnMrChips.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMrChips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mrchips.jpeg"))); // NOI18N
        jbtnMrChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMrChipsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMrChips, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 270, 170));

        jbtnCoke.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCoke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/coke in a can.jpg"))); // NOI18N
        jbtnCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCokeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 270, 170));

        jbtnPepsi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPepsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pepsi in a can.jpg"))); // NOI18N
        jbtnPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPepsiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 270, 170));

        jbtnSprite.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sprite in a can.jpg"))); // NOI18N
        jbtnSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpriteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 270, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 730));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 170, 60));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 170, 60));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 170, 60));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 170, 60));

        jtxtTotal1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtxtTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotal1ActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 60));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 270, 120));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 50));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment Method: Cash Only");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cash");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 50));

        jtxtCash.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jtxtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCashActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Change");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 720, 300));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mini Store POS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 720, 110));

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, 240, 290));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 470, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnWilkinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWilkinsActionPerformed
      double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Wilkins Bottle", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnWilkinsActionPerformed

    private void jbtnPiatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPiatosActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Piatos Cheese", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnPiatosActionPerformed

    private void jbtnChippyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChippyActionPerformed
         double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chippy Barbecue", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChippyActionPerformed

    private void jbtnNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovaActionPerformed
         double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nova BBQ", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnNovaActionPerformed

    private void jbtnMrChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMrChipsActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Mr.Chips Mac&Cheese", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnMrChipsActionPerformed

    private void jbtnCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCokeActionPerformed
       double PriceOfItem = 32;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coke Can", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnCokeActionPerformed

    private void jbtnPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPepsiActionPerformed
        double PriceOfItem = 31.25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pepsi Can", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnPepsiActionPerformed

    private void jbtnSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpriteActionPerformed
         double PriceOfItem = 32.15;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sprite Can", "1", PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnSpriteActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try {
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        jtxtTotal1.setText("");
        jtxtCash.setText("");
        jtxtChange.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
      
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
                
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      
      int RemoveItem = jTable1.getSelectedRow();
      if(RemoveItem >= 0)
      {
          model.removeRow(RemoveItem);
      }
      
      ItemCost();
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
  int cash,total;
  
  cash = Integer.parseInt(jtxtCash.getText());
 
  
  if (cash < 0) {
      
       JOptionPane.showMessageDialog(null,"Invalid Cash Please Add More or Pay Higher", "Title", JOptionPane.PLAIN_MESSAGE);
  }
  else {
          Change();
            bill();
       
  } 
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
     
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotal1ActionPerformed

    private void jtxtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnChippy;
    private javax.swing.JButton jbtnCoke;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnMrChips;
    private javax.swing.JButton jbtnNova;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPepsi;
    private javax.swing.JButton jbtnPiatos;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSprite;
    private javax.swing.JButton jbtnWilkins;
    private javax.swing.JTextField jtxtCash;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtTotal1;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
